### ISSUE TITLE
Videos with captions make FFMPEG hang

### ISSUE THREAD

**Issue by harrydayexe** [aidandenlinger/SnapchatMemoriesMetadataAdder#14]
Not sure if this is an issue with FFMPEG or the tool itself, I have successfully exported >2000 photos with captions and metadata using the `--photos-only` flag. When I have gone to do the same with videos, the program hangs around 65ish photos in. After running with verbose output it appears to be the FFMPEG threads that are hanging.

Running the latest commit `d41dae0` 

Log output with `-vv` can be seen in this gist: https://gist.github.com/harrydayexe/45186d516f3bc7a00a5c9c77c447a15e

I have tried a few different modifications to the FFMPEG command but none have seemed to work.

hw: MacBook Pro M4 (14 cores) with 48GB RAM
os: macOS Sequoia 15.1.1 arm64

**Comment by harrydayexe** [comment]
The most interesting part of the logs are right at the bottom where FFMPEG keeps reporting a slower speed with no changes in frame etc:

`frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:01.39 bitrate=   0.3kbits/s speed=1.34x    `

**Comment by harrydayexe** [comment]
interestingly if I press q when ffmpeg hangs I get the following error log before it continues:

`[out#0/mp4 @ 0x600002109c80] Nothing was written into output file, because at least one of its streams received no packets.`

**Comment by harrydayexe** [comment]
Doing a bit of debugging and added this PR to see the ffmpeg command that will be run: https://github.com/aidandenlinger/SnapchatMemoriesCaptionAdder/pull/15

From this I can see on one of the videos that hangs, that indeed it still hangs when ran manually indicating this may be a problem with the command itself or possibly my installation of FFMPEG

**Comment by harrydayexe** [comment]
A fresh install of FFMPEG@6 from brew has not solved this issue

**Comment by harrydayexe** [comment]
Ah after looking at what is output before I kill the program it appears that only the videos that do not have overlays work, and once every core is processing a video with a caption the program hangs

**Comment by aidandenlinger** [comment]
Fascinating - https://github.com/aidandenlinger/SnapchatMemoriesCaptionAdder/issues/11#issuecomment-2500276930 is running this script on Windows and also running into a hanging FFMPEG situation. Not sure if your situation is the same, but two people running into a weird ffmpeg issue makes me think it's likely something wrong with the script more than your individual setups.

> that indeed it still hangs when ran manually indicating this may be a problem with the command itself

This is probably the case. I'm trying to think about variables that have changed since I haven't touched that ffmpeg code in forever and now it's hanging:
- maybe the Snapchat export has changed in some way compared to how it used to be?
- I don't think it's a new `ffmpeg` release, but maybe there was a new point release of 6.1 that changed its behavior?

I'm thinking it's most likely something about the Snapchat export though, if at least one of the streams isn't receiving data I wonder if I'm using a now incorrect file name somewhere (probably the caption, since the uncaptioned videos are fine) and thus that stream isn't getting any data.

I'll be thinking about this, but if you discover anything new please feel free to update here and/or make a PR. (At the end of the day, I probably just need to hunker down and do #7 )

**Comment by harrydayexe** [comment]
I have been experimenting with ffmpeg commands on their own and have figured out how to do this with ffmpeg 7 using the scale command and have successfully scaled and overlayed. Working on getting this working through the python lib now. PR pending...

**Comment by harrydayexe** [comment]
I've only gone and done it! Running against my own videos now as a test and then I'll push a PR

**Comment by harrydayexe** [comment]
Fix live at https://github.com/aidandenlinger/SnapchatMemoriesCaptionAdder/pull/16
