### ISSUE TITLE
Unclear Configurations for Snapchat Data Export

### ISSUE THREAD

**Issue by jxakellis** [aidandenlinger/SnapchatMemoriesMetadataAdder#8]
Hi,

When exporting my Snapchat data from the "Download my Data" portal, I was slightly unclear about the required configurations. This is because there are two different options to select to include/exclude Memories. As you only get two data exports from Snapchat every 24 hours, I wanted to ensure I chose the correct options. Attached are the screenshots of what I presume are the proper configurations for the two exports. Let me know if I'm on the right track (and possibly clarify instructions for other future users)

The rest of the guide is straightforward and looks great!

- Jonathan

<img width="675" alt="Screenshot 2024-06-21 at 12 18 03 PM" src="https://github.com/aidandenlinger/SnapchatMemoriesCaptionAdder/assets/68080954/6ec0974e-6f37-49d5-afce-244b4e06fe4b">
<img width="959" alt="Screenshot 2024-06-21 at 1 46 44 PM" src="https://github.com/aidandenlinger/SnapchatMemoriesCaptionAdder/assets/68080954/aebb8388-eaa4-4e34-8a11-746ef11783af">

**Comment by aidandenlinger** [comment]
Ooh, they've clearly updated these options since the last time I did this! I think when I did this, it was literally just the "Include your Memories" checkbox. Thanks for bringing this to my attention, will update the instructions once we figure out what works here :)

The script only need two things:
- your actual memories, which should be that top option, "Include your Memories, Chat Media and Shared Stories"
- The `memories_history.json` file, which has all the metadata we want to attach, and I think is controlled by that second option "Memories And Other Media".

So I'm going to be optimistic and say maybe we can get both in one export now? Try the second screenshot, which has both the "Include your Memories..." box at the top and the second "Memories and Other Media" option checked, and hopefully you get both in one export and the instructions can become simpler :)

If that export doesn't include the `memories_history.json` file, then for the second export try doing it *without* the "Include your Memories..." option from the top and only clicking that second "Memories and Other Media" box at the bottom.

And let me know how it turns out so I can update the README!

**Comment by aidandenlinger** [comment]
I found a similar issue in a similar project, ToTheMax/Snapchat-All-Memories-Downloader#78. In short, yeah it looks like even with the shiny new panel it still acts like it did before, and if you use the "Include your Memories" option it won't generate `memories_history.json`.

So I'd expect you to have to do two exports:
- once with "Include your Memories" (to get the actual memory files)
- once *without* "Include your Memories", and with that second option "Memories and Other Media" checked. (to get memories_history.json)

It'd be a nice surprise if checking both included both though! So keep me posted on what ends up working :)

**Comment by jxakellis** [comment]
Looks like you're correct. To follow up with the new verbiage, these are the two exports I did that made it work. 

Export 1
- YES: Include your Memories, Chat Media and Shared Stories
- YES: Export JSON Files
- YES*: Memories And Other Media
* For this first export, this option may be able to be set to off
- NO: Everything else
- For the date range of data, anything works. No date range (all data) or a specific date range

Export 2
- YES: Export JSON Files
- YES*: Memories And Other Media
* For this second export, this option has to be set to on
- NO: Everything else
- For the date range, select the same option as the previous export

To make the project work, we still need two exports. Even if you select "Memories And Other Media" in the first export, the memories_history.json file is not included. Instead, even though JSON format is selected, a memories.html file is included. Thus, the second export gets us that required memories_history.json file

**Comment by aidandenlinger** [comment]
Thanks for your help! Just updated the README with this information :) I went optimistic with the state of the other checkmarks not mattering, I'll deal with any future issues.
